### ISSUE TITLE
Document JLV VPR invocations (ie/ arguments passed) 

### ISSUE THREAD

**Issue by conorcaregraf** [vistadataproject/VDM#101]
JLV has display data largely (now) using VPR XML ...

![image](https://cloud.githubusercontent.com/assets/1831390/16750998/d2a8bf38-478a-11e6-8780-18d2f2a67067.png)

__Requirement__: document here all VPR variations (domain ids, arguments) used by JLV.

__Interface Agreement to examine and add__: Sean says JLV has one (what RPCs used and how). Will go through and add details here.

**Comment by conorcaregraf** [comment]
## The 3 demo domains - Problem, Vital, Allergy 

__Background__: first three to describe as these are our first "demo domains" (we will add Patient/Demographics soon).

**Comment by sishiihrg** [comment]
JLV methods and RPCs used for Problems, Vitals, and Allergies

getPatientProblemList
VPR GET PATIENT DATA
Parameters: problems, startDate, endDate

getPatientVitals	
VPR GET PATIENT DATA
Parameters: vitals, startDate, endDate

getPatientAllergies
VPR GET PATIENT DATA
Parameters: reactions, startDate, endDate

**Comment by sishiihrg** [comment]
One of the more recent VistaDataService ICD. See Appendix B.

[JLV_2.4.0.1_VistA_Data_Service_ICD.docx](https://github.com/vistadataproject/VDM/files/372732/JLV_2.4.0.1_VistA_Data_Service_ICD.docx)

**Comment by conorcaregraf** [comment]
moved into VPR issue proper
