### ISSUE TITLE
Check MVDM form (JSON-LD) against hydra interface

### ISSUE THREAD

**Issue by conorcaregraf** [vistadataproject/VDM#123]
http://www.hydra-cg.com/spec/latest/core/

see that MVDM fits in.

**Comment by rafael5** [comment]
See links/documentation:

http://www.markus-lanthaler.com/research/third-generation-web-apis-bridging-the-gap-between-rest-and-linked-data.pdf

http://www.markus-lanthaler.com/research/on-using-json-ld-to-create-evolvable-restful-services.pdf

http://www.markus-lanthaler.com/research/seamless-integration-of-restful-services-into-the-web-of-data.pdf
