### ISSUE TITLE
*Investigate*  Hydra:   Web APIs auto-generated from MVDM (JSON-LD)

### ISSUE THREAD

**Issue by rafael5** [vistadataproject/VDM#124]
### _Investigate_  Hydra:   Web APIs auto-generated from MVDM (JSON-LD)

See links/documentation:
http://www.hydra-cg.com/spec/latest/core/

http://www.markus-lanthaler.com/research/third-generation-web-apis-bridging-the-gap-between-rest-and-linked-data.pdf

http://www.markus-lanthaler.com/research/on-using-json-ld-to-create-evolvable-restful-services.pdf

http://www.markus-lanthaler.com/research/seamless-integration-of-restful-services-into-the-web-of-data.pdf

**Comment by conorcaregraf** [comment]
moved
