### ISSUE TITLE
Test with latest ecmascript

### ISSUE THREAD

**Issue by conorcaregraf** [vistadataproject/VDM#151]
REM: advantage is we're doing server-side JS => can go with latest of node as only it and not many browser engines need to run the code.

Only hold back: the cache.node and gtm node.js drivers for accessing MUMPS. Need an isolation test.

Note: does latest support the likes of 
  * [template strings](https://developers.google.com/web/updates/2015/01/ES6-Template-Strings?hl=en)
  * [let](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/let)
etc.

**Comment by sbruno81** [comment]
Based on testing on Ubuntu 16.04, the nodem library supports up to Node version 4.7.0 LTS. The nodem installation failed when utilizing Node v6.9.2 LTS.

Node v4.7.0 offers many benefits over the previous version that VDS employed, which was v0.12.17.

This [article](http://apmblog.dynatrace.com/2015/09/05/all-you-need-to-know-about-node-js-4-0/)  from Sept. 2015 highlights many of the v4.0.0+ improvements.

Here are some highlights:

- **New V8 Version: v4.5 (v5.x is current)**
- **Extended ES6 Support**
     - Block scoping using let and const
     - Classes
     - Generators
     - See [ES6 and beyond](https://nodejs.org/en/docs/es6/)
- **Performance Enhancements**
   - Newer versions of V8 come with JS performance optimizations
- **Long Term Support (LTS) Versions**
   - There will be LTS releases every 12 months
   - Every LTS version will be active for this 12 months
   - After that every LTS version will be in maintenance mode for another 18 months

**Comment by conorcaregraf** [comment]
MOVED TO issue tracking coding standards in general.
