### ISSUE TITLE
MVDM:  Support OIT mandate:  "Public VISTA API"  for class2/3 interfacing

### ISSUE THREAD

**Issue by rafael5** [vistadataproject/VDM#162]
# MVDM to create public VISTA APIs
This will support OIT mandate:  "all Class 2/3 software can only interface via VISTA API"

Per OIT EPMO:
"The OI&T Enterprise Program Management Office does not endorse nor support Class 2 and Class 3 products and does not support data usage or application programmer interfaces (APIs) between Class 1 National Software products and Class 2 or Class 3 products.  __Class 2 or Class 3 products must restrict their interfaces to Class 1 National Software to use of publicly-supported APIs ONLY."__

The original text of this was found on the VA TRM:
http://www.va.gov/TRM/ToolPage.asp?tid=7557

=> Issue: MVDM shall create a  'publicly-supported VISTA API'.
Then we  can drive all class 2 / class 3 software through MVDM, per the above mandate.

p.s. what does 'publicly-supported' mean?  Does it mean 'public-facing'?

**Comment by conorcaregraf** [comment]
this issue list is for in depth requirements - moving to documents.

**Comment by rafael5** [comment]
Gotcha.

Strategically:  the only  'public-facing API'  available in VA now  that of
HMP, and its not even a ViSTA interface; it is a read-only VDP interface.

So:  This means that MVDM's  generated APIs will bre the only game in
town.  Right?



Rafael


*Rafael Richards MD MS*
*202-469-1527*

**Comment by whitten** [comment]
I expect by "PUBLIC" supported APIs are those that are marked "PUBLIC" in the Database Integration Agreements published by the VA.  These are also called IA and ICR 
the list is available as a text document or a Web document at http://code.osehra.org/vivian/files/All-ICR%20List.html

**Comment by conorcaregraf** [comment]
issue in documents - see: https://github.com/vistadataproject/documents/issues/46 (moved Dave's comment there too)

**Comment by rafael5** [comment]
In the context of interfacing to class 2 and class 3 software.... COTS
add-ons and the outermost 'warts'  as depicted in the VISTA onion
diagram....  wouldn't the term "public API" mean "external API" in the
contemporary, common vocabulary... Not the internal VISTA-ese?


In that case it is means what eHMP has done creating an SDK with APIs...
