### ISSUE TITLE
Parameter Documents (to join other web site dev docs)

### ISSUE THREAD

**Issue by conorcaregraf** [vistadataproject/VDM#180]
__Source__: JSON from nodeVISTA - at https://github.com/vistadataproject/VDM/blob/master/definitions/RPC/json/nodeVISTAParameters.json
__Go into__: artifacts/parameters (peer of rpcL etc)
__Note__: rpcL enhancement will list parameters and files used by RPCs. These enhancements can link to VDM and Parameter docs.

**Comment by mfuroyama** [comment]
Implemented a new document generator module in `definitions/docs`: https://github.com/vistadataproject/VDM/pull/236

### Notes
The generator creates individual Markdown files for each parameter and also generates a table of contents Markdown file which references all the other generated Markdown.

The `parameterDocGenerator` module is dual-use: The generator class definition can be `require`'d as a module, or can be run directly as a script (with command line options)

### Screenshots
_Sample parameter description_
![2017-04-13_1008](https://cloud.githubusercontent.com/assets/728376/25022888/64866b68-2033-11e7-94b6-1062056e24d6.png)

_Sample table of contents_
![2017-04-13_1013](https://cloud.githubusercontent.com/assets/728376/25022937/959acce4-2033-11e7-9418-e33c18105375.png)
