### ISSUE TITLE
MVDM Patient loading issues - shows issues in FileMan or VDM

### ISSUE THREAD

**Issue by sbruno81** [vistadataproject/VDM#198]
- [ ] trigger on address create fails to set user and facility
- [ ] confidential phone number causes fileMan error

The VDM patient model contains a trigger on fmId .118 address change dt/tm. This trigger will set/update various fields that are associated with the patient's address (location 11;*).

Two of the fields set by this trigger are .12 address change site and .122 address change user. Both of these fields are not being set/updated correctly by the trigger. Particularly, address change user sets the value to DUZ=0.

**Comment by sbruno81** [comment]
Setting the patient field confidential_phone_number causes a fileman error:

FIRE+8^DIEF,%GTM-E-UNDEF, Undefined local variable: DFN

**Comment by conorcaregraf** [comment]
fixed - set DUZ and DFN explicitly.
