### ISSUE TITLE
Patient Record Flags

### ISSUE THREAD

**Issue by sbruno81** [vistadataproject/VDM#207]
__NO MILESTONE as may not fall under VDP 2__

(May revisit as VA specific data - but not in 1.4 for now)

__Note__: separate prototype from base patient prototype. Key for highlighting management of behavioral issues.

  * [guide](https://www.va.gov/vdl/documents/Clinical/Patient_Record_Flags/patrecflagug.doc)

## Patient Record Flags (PRFs)

**RPC**: _ORPRF HASFLG_ which calls through _GETACT^DGPFAPI_ to _GETALL^DGPFAA_ . See MUMPS banner for info - [DGPFAPI](https://github.com/OSEHRA/VistA-M/blob/master/Packages/Registration/Routines/DGPFAPI.m)
**Patient File**: [26_13](http://localhost:9000/schema#26_13) PRF Assignment
**Audit File**: [26_14](http://localhost:9000/schema#26_14) ... will have to manage as insert 26.13 with MVDM/VDM.
**Meta K Files**: [26_15](http://localhost:9000/schema#26_15) and [26_11](http://localhost:9000/schema#26_11), the flags assigned to patients. 26_11 is NATIONAL ie/ VA wide created flags while 26_11 is local. nodeVISTA has no locals but there are four nationals. __Gotta grab clone's local flags and compare to nodeVISTA__

Look at the [CPRS GUI Guide](https://github.com/caregraf/fmqle/files/671978/cprsguium.pdf) which has a section on this.

__TIU TOO:__ besides these RPCs, TIU has _TIU ISPRF_ and _TIU GET LINKED PRF NOTES_ - this MAY require expansion of our basic, allergy-supporting Note prototype.

Note that most of the PRF logic is in code written before RPCs => internal/option thing and these RPCs (which have 'order' names) were add ons.

VISTA allows flags like "BEHAVIOR" to be assigned to a patient when he is registered. nodeVISTA lacks settings for any of its patients. 

**TODO**:
1. assign a flag (ex/ BEHAVIOR - see screen shot below) to one of the patients
   - this means creating (through VDM) a PRF entry
   - must add PRF to the VDM Model of Patient and add it to MVDM Patient Model
2. see what ORPRF HAS FLG returns and see how CPRS behaves (different highlights?)
3. VPR and PRF
4. tie into the documents/notes - _TIU GET LINKED PRF NOTES_ etc

ex/ of flag in 25_11 ...

![screen shot 2016-11-11 at 10 30 00 am](https://cloud.githubusercontent.com/assets/1831390/20225962/dde6ea8e-a7fa-11e6-8b91-1862dab81816.png)

Flag RPCs

| RPC | Description |
| --- | --- |
| ORPRF HASFLG | National or local flags. 26.11/26.15 files. This returns flags of patient and also sets up TMP with those flags for use by GETFLG |
| ORPRF GETFLG | # relies on HASFLG setup |
| ORPRF TRIGGER POPUP | # for CPRS - should it trigger a popup because patient has flags - 1 or 0 |
| ORPRF CLEAR | "Clears up the ORPRF TMP global set by HASFLG |

Note: **we will NOT LOCK these in the first pass**. _HASFLG_ setups a TMP (cache for current patient). Need to see if want to support such "optimizations" and **inter-RPC setups**.

**Comment by sbruno81** [comment]
###PRFs can be entered through the progress notes entry in CPRS:###
![screen shot 2017-03-15 at 4 23 14 pm](https://cloud.githubusercontent.com/assets/1563709/23975293/c4624e36-09ad-11e7-851b-35c0b9304771.png)

**Comment by conorcaregraf** [comment]
## From VA Doc

[Doc](https://www.va.gov/vdl/documents/Clinical/Patient_Record_Flags/patient_record_flags_user_guide.pdf)

![screen shot 2017-03-15 at 5 30 03 pm](https://cloud.githubusercontent.com/assets/1831390/23976608/19213a5c-09a6-11e7-8751-785de471d9e5.png)

![screen shot 2017-03-15 at 5 30 35 pm](https://cloud.githubusercontent.com/assets/1831390/23976610/1ecf7f9a-09a6-11e7-8b97-043ded4f4bb3.png)

PRF covered by formal policy letters ...

![screen shot 2017-03-15 at 5 31 05 pm](https://cloud.githubusercontent.com/assets/1831390/23976616/251edd6e-09a6-11e7-80ff-e3b26872cc63.png)

TIU note tie in ...

![screen shot 2017-03-15 at 5 32 01 pm](https://cloud.githubusercontent.com/assets/1831390/23976635/36f12d94-09a6-11e7-843a-0fb12fceac4f.png)

**Comment by conorcaregraf** [comment]
## More on Progress note tie in

26.15/National flag definition has

![screen shot 2017-03-15 at 5 42 43 pm](https://cloud.githubusercontent.com/assets/1831390/23976722/e50e0dca-09a6-11e7-8969-8b6c896d0ed6.png)

ex ...

![screen shot 2017-03-15 at 5 42 43 pm](https://cloud.githubusercontent.com/assets/1831390/23976755/1d0fe5e0-09a7-11e7-8962-656f46b1330e.png)

ie/ flag definition references note. Question is how is this used ie/ does note lead to flag? Or flag, note. How is flag entered?

**Comment by conorcaregraf** [comment]
Patient PRF RPCs

![screen shot 2017-03-15 at 5 49 39 pm](https://cloud.githubusercontent.com/assets/1831390/23976862/cea1dc46-09a7-11e7-894e-613aca605dfd.png)

![screen shot 2017-03-15 at 5 50 18 pm](https://cloud.githubusercontent.com/assets/1831390/23976880/e556120e-09a7-11e7-8508-a344ee06af8e.png)

**Comment by conorcaregraf** [comment]
## Created in Roll and Scroll

See [CPRS User Guide](https://www.va.gov/vdl/documents/Clinical/Comp_Patient_Recrd_Sys_(CPRS)/cprsguium.pdf)

![screen shot 2017-03-16 at 12 25 23 pm](https://cloud.githubusercontent.com/assets/1831390/24015295/59cccfea-0a45-11e7-987e-7e9954f6dcd2.png)

docs use CPRS to write progress notes explaining clinical bg.

![screen shot 2017-03-16 at 12 25 31 pm](https://cloud.githubusercontent.com/assets/1831390/24015326/6a0fe19e-0a45-11e7-9760-b9a0751d950b.png)

and need permission (does Robert have it?) to write Class I notes ....

![screen shot 2017-03-16 at 12 26 40 pm](https://cloud.githubusercontent.com/assets/1831390/24015343/7ad96306-0a45-11e7-8c7b-1fd305e7b884.png)

Note that PRFs themselves  have the usual __create, update, remove (entered in error), unremove ...__ seen elsewhere.

![screen shot 2017-03-16 at 12 40 26 pm](https://cloud.githubusercontent.com/assets/1831390/24015517/f172c980-0a45-11e7-81ff-1ce35776bf3c.png)

**Comment by conorcaregraf** [comment]
## Some Activation code and PARAMETER

```text
GMTSMHRF ;BP/WAT - DRIVER FOR PRF ASSIGNMENT HX ;09/05/12  13:47
 ;;2.7;Health Summary;**99,104**;Oct 20, 1995;Build 38
 ;
...
 S FLGNAME="HIGH RISK FOR SUICIDE"
 S FLGPTR=$$GETFLAG^DGPFAPIU(FLGNAME,"N"),CAT="NATIONAL"
 I $G(FLGPTR)["-1" S CATEGORY="I",ERRMSG=$P(FLGPTR,";",2) D ERR Q
 S RESULT=$$GETINF^DGPFAPIH(DFN,FLGPTR,,,"GMTSARR")
 I $G(RESULT) S GMTSSTAT=$$GETSTAT(FLGNAME,CAT) D PRINT S RESULT=0
 S FLGNAME=$$GET^XPAR("PKG","DGPF SUICIDE FLAG",1,"E")
...
```

where [DGPF SUICIDE FLAG](http://localhost:9000/query?fmql=DESCRIBE%208989_51-642&format=HTML)

... don't see others yet.

**Comment by conorcaregraf** [comment]
## Interplay with HL7 - level 1 flags

> Category I PRF become national information as part of the Master Patient Index and is displayed at all VHA facilities where the patient is registered. As a result, patients with a Category I PRF who present an immediate safety risk for seriously disruptive, threatening, or violent behavior, may be safely treated within VHA wherever they are registered and seek care.

**Comment by conorcaregraf** [comment]
moved to sync git
