### ISSUE TITLE
8994 required is always true

### ISSUE THREAD

**Issue by conorcaregraf** [vistadataproject/VDM#46]
ex/ 

```text
        {
          "id": "8994_02-3_97",
          "type": "vs:Input_Parameter-8994_02",
          "input_parameter-8994_02": "VDT",
          "parameter_type-8994_02": "LITERAL",
          "required-8994_02": true,
          "description-8994_02": "This optional parameter is the Date/time of visit.  If the parameter VSITis present, this will be ignored.  Otherwise, the RPC will attempt togenerate a match with a visit based on DFN, VDT, and VLOC (visitlocation).  In the event that the RPC cannot generate such a match, a newEVENT-type Visit will be created with the current date/time."
        },
```

... should be false. It is in the Rambler.

**Comment by whitten** [comment]
Is the JSON "required-8994_02" signifying 

a) that the REQUIRED field #.04 in the INPUT PARAMETER field #2 (sub-file #8994.02) of the REMOTE PROCEDURE File #8992 has an INTERNAL value of 1 (EXTERNAL value of YES)

b) that the "R" chararcter is in the value of the ATTRIBUTE called SPECIFIER of the INPUT PARAMETER Field #.01 in the INPUT PARAMETER field #2 (sub-file #8994.02) of the REMOTE PROCEDURE File #8992

or does it mean something different beyond ?

PS: what does the "id": "8994_02-3_97", signify ? 
I didn't see the number 3.97 anywhere.
