### ISSUE TITLE
mongoose prototype to re-implement MVDM allergy prototype

### ISSUE THREAD

**Issue by conorcaregraf** [vistadataproject/VDM#51]
__Background__: three routes to create/update in Node.js-enabled VISTA:
  * Legacy RPCs (opaque, unreliable, inconsistent)
  * Mixed JS/MUMPS - JS backed by select logic called by RPCs (mixed model)
  * Pure JS with same data effects as the first two routes

and the first major prototype, ["Observed Allergies MVDM"](https://github.com/vistadataproject/VDM/tree/master/prototypes/allergies) explores all three.

Changed appropriately, the pure JS prototype (ex/ don't ultimately call FileMan UPDATE^DIE but insert into MongoDB) should work over Mongo AND a variation fully re-implemented using Mongoose should have the same data forms. This Mongoose variation can inform improvements in the VDM and MVDM modules - facilities in Mongoose can be emulated in those modules.

Pacing: 
  1. start first with the simple VDM-only, Allergy spec, https://github.com/vistadataproject/VDM/blob/master/prototypes/allergies/vdmAllergies-spec.js and its visit and document counterparts. 
  2. once they work, move on to the full MVDM allergies spec which tests MVDM's ability to create all three types of object.
  3. try to restructure VDM.js (in a "VDM_Mongoose") to support events/singleton pattern ala Mongoose (see comment below)

Ex Mongoose facilities to leverage/examine:
  * singleton 
  * update events
  * schema definition (nuance)
  * how JS checks and behaviors are defined and introduced

__Where__: [mongoose prototype](https://github.com/vistadataproject/VDM/blob/master/prototypes/mongoose/README.md)

__When__: in time for second Technical Report due end of May.

**Comment by conorcaregraf** [comment]
## VDM as a singleton ala Mongoose

One thing to examine is how better to structure the VDM singleton - https://github.com/vistadataproject/VDM/blob/master/prototypes/vdm.js

ala mongoose (http://bites.goodeggs.com/posts/export-this/#global_object)
 *   ... look at basic mongoose interaction/setup
 *   ... .model() ... new A.

issue with event emitter if use singleton pattern
 * http://stackoverflow.com/questions/13466227/nodejs-singleton-events

Mongoose can do it but caused issue for VDM singleton (must be some trick!)
  * // var EventEmitter = require('events').EventEmitter;

**Comment by sbruno81** [comment]
https://github.com/vistadataproject/VDM/tree/master/prototypes/mongoose

**Comment by sbruno81** [comment]
Analysis:

https://github.com/vistadataproject/VDM/wiki/VDM-vs-Mongoose-Analysis

**Comment by sbruno81** [comment]
Event emitter was added to VDM. Below is an example of VDM create events handling in vdmAllergies-spec.js:

```javascript
it("Historical Allergy - test that create event is firing", function(done) {

     var retModel;

     var SpyObj = { //dummy spy object
         vdmCreateSpy: function() {
             //method used to test whether VDM 'create' event was called.
         }
     };

     spyOn(SpyObj, 'vdmCreateSpy');

     VDM.once('create', function(vdmModel) {
         retModel = vdmModel;
         SpyObj.vdmCreateSpy();
     });

     VDM.create(testAllergies.historicals.one.vdmCreate);

     _.delay(function() {
         expect(SpyObj.vdmCreateSpy).toHaveBeenCalled();
         expect(SpyObj.vdmCreateSpy.calls.count()).toEqual(1);
         expect(SpyObj.vdmCreateSpy.calls.count()).not.toEqual(2);
         expect(retModel).toBeDefined();
         // reactant from gmr_allergy
         expect(retModel.reactant).toEqual(retModel.gmr_allergy.label);
         done();
     }, 100);
   });
```
