### ISSUE TITLE
AINA Patient Data - QA against/test VDM

### ISSUE THREAD

**Issue by conorcaregraf** [vistadataproject/VDM#60]
## Basic patterns ...

```

# 120.8's 872

	# HISTORICAL 716
		Overall Mandatories
			WARNING - missing mandatory originator-120_8 37
			WARNING - missing mandatory verified-120_8 14
		Average # of fields 17.3142458101
		Max # of fields 23
		Min # of fields 12
		By Allergy Type:
			DF 172
			D 374
			O 37
			F 133
		Entered in error 147
			All Mandatories present
		Verified
			Number True 702
			WARNING - missing mandatory verification_date_time-120_8 36

	# OBSERVED 150
		Overall Mandatories
			WARNING - missing mandatory verified-120_8 5
		Average # of fields 18.02
		Max # of fields 23
		Min # of fields 14
		By Allergy Type:
			DF 39
			D 83
			O 10
			F 18
		Entered in error 46
			All Mandatories present
		Verified
			Number True 145
			WARNING - missing mandatory verification_date_time-120_8 33
		Missing comments 86 ... surprising as forced by CPRS!

	# NO OBS or HIST Value 6
```

**Comment by whitten** [comment]
What is the program you used to analyze this summary file for FILE #120.8?

Also, it might be useful if you ran on files like 120.5 which
has a limited access to change, that you look for
text like this in the DESCRIPTION of the FILE and 
marked the file in some way so this overview would mention
the "locked down" status.

Per VHA Directive {pending directive #}, this file has been "locked down" by
Data Standardization (DS). The file definition (i.e. data dictionary) shall not
be modified. All additions, changes and deletions to entries in the file shall
be done by Enterprise Reference Terminology (ERT) using the Master File Server
(MFS), provided by Common Services (CS). Creating and/or editing locally
defined fields in the file are not permitted. Use of locally defined fields
that were created prior to VHA Directive {pending directive #} shall not be
supported.

**Comment by conorcaregraf** [comment]
Basic analysis code set up (https://github.com/vistadataproject/VDM/tree/master/clones) and data isolated (https://github.com/vistadataproject/VDM/blob/master/clones/observedAllergyMVDMTestData.json).

**Comment by conorcaregraf** [comment]
Replaced by more generic issue - https://github.com/vistadataproject/VDM/issues/72

**Comment by conorcaregraf** [comment]
Replaced by more generic issue - https://github.com/vistadataproject/VDM/issues/72
