### ISSUE TITLE
Security - PIKS

### ISSUE THREAD

**Issue by conorcaregraf** [vistadataproject/VDM#62]
## Tease out Data-Centric vs/over existing security

From Dave Whitten ...

```text
The security is usually on  a data-column or a data-field and all the data stored with that definition.   This security is either M-Code or the DUZ(0) security or is the Kernel8 File Access Security (ACCESSIBLE FILE multiple in NEW PERSON FILE).  There is no SECURITY KEY security on columns. (SECURITY KEYS are on OPTIONS & PROTOCOLs)  The FOF security is setup on each person's record. 

The DUZ(0) security is optionally setup on each Column/Field. There is READ ACCESS and WRITE ACCESS and DELETE ACCESS.  There is also M Code security on DELETE and LAYGO

The kinds of DUZ(0) security that can be setup for a FILE are: AUDIT, 
DATA DICTIONARY, DELETE, LAYGO (adding new data records), 
READ, DATA DICTIONARY AUDIT and WRITE access.

The kinds of M-Code security are DELETE, LAYGO, and AUDIT.
```

**Comment by hschema** [comment]
Copied into Sublime, and pasted back to Github so wordwrap works:

The security is usually on  a data-column or a data-field and all the data stored with that definition.   This security is either M-Code or the DUZ(0) security or is the Kernel8 File Access Security (ACCESSIBLE FILE multiple in NEW PERSON FILE).  There is no SECURITY KEY security on columns. (SECURITY KEYS are on OPTIONS & PROTOCOLs)  The FOF security is setup on each person's record. 

The DUZ(0) security is optionally setup on each Column/Field. There is READ ACCESS and WRITE ACCESS and DELETE ACCESS.  There is also M Code security on DELETE and LAYGO

The kinds of DUZ(0) security that can be setup for a FILE are: AUDIT, 
DATA DICTIONARY, DELETE, LAYGO (adding new data records), 
READ, DATA DICTIONARY AUDIT and WRITE access.

The kinds of M-Code security are DELETE, LAYGO, and AUDIT.

**Comment by conorcaregraf** [comment]
## PIKS Generic

  * K files - must include all 4.005 files (ie/ meta data updated through remote servers)
