### ISSUE TITLE
Graphic of % VISTA data accessibility:  VDM query   vs  VPR / CPRS / RPCs

### ISSUE THREAD

**Issue by rafael5** [vistadataproject/VDM#64]
### Graphic of % VISTA data access:  VDM query    vs  VPR /  CPRS  RPCs

Pie Chart showing accesibility of VISTA data:
* VDM:  100%  (65,000 fields)
* VPR:  1%    (440 fields)
* CPRS: %     (?? fields from 1000 RPCs?)
* RPCs   %     (?? fields from 3300 RPCs?)

Questions: 
1. Can we quantify RPC coverage of VSTA data access? i.e. 
2. CPRS coverage =  1000 RPC coverage = ??

**Comment by whitten** [comment]
I think we can quantify the level of coverage of REMOTE PROCEDUREs used by CPRS,
but only if we have a separate category for each version of CPRS.
Loading the CPRS Source code would allow one to find each of the calls from CPRS.
Probably a simple text search as they are all invoked using the same subroutine to
call the REMOTE PROCEDURE.

**Comment by conorcaregraf** [comment]
moved to scoping numbers
