### ISSUE TITLE
VDM error event handling

### ISSUE THREAD

**Issue by sbruno81** [vistadataproject/VDM#80]
> When an error occurs within an EventEmitter instance, the typical action is for an 'error' event to be emitted. These are treated as a special case within Node.js.
> 
> If an EventEmitter does not have at least one listener registered for the 'error' event, and an 'error' event is emitted, the error is thrown, a stack trace is printed, and the Node.js process exits.

See [Error Events](https://nodejs.org/api/events.html#events_error_events)

If applied to VDM's create method, an exception is thrown and the client never receives the expected return object containing the error.

line 119 of VDM.js:

``` javascript
if (!res.valid) { 

  //throws an exception or emits event if there's at least one registered listener
  this.emit('error', res.details);

  //never gets returned 
  return {"error": res.details}; 
} 
```

Some thoughts:
- [From a Joyent article on error handling best practices](https://www.joyent.com/developers/node/design/errors):

> The general rule is that a function may deliver operational errors synchronously (e.g., by throwing) or asynchronously (by passing them to a callback or emitting error on an EventEmitter), but it should not do both. This way, a user can handle errors by either handling them in the callback or using try/catch, but they never need to do both. Which one they use depends on what how the function delivers its errors, and that should be specified with its documentation.
- Errors should be wrapped in an Error object (i.e. new Error(...) ).

**Comment by conorcaregraf** [comment]
gotta use _expect.toThrow_ in all our jasmine tests.

**Comment by conorcaregraf** [comment]
From Steve:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error

```text
“The Error object can also be used as a base object for user-defined exceptions. See below for standard built-in error types.”
 
Maybe we could have VDM specific error types? 
```

... we can establish some basic types - vdmUtils and mvdmUtils do have five or six clear cut errors that look for (invalid reference, can't set dependent property etc).

**Comment by conorcaregraf** [comment]
moved to code standards.
